# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

stages:
- stage: publish
  jobs:
  - job: Web_publish
    pool: HR-Self Hosted  
    variables: 
      LastUpdateDate: $[format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime)]

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          if (!(Test-Path "\\ncrws541\DEV\WAA\App_Offline.htm"))
          {
             New-Item -Path "\\ncrws541\DEV\WAA" -Name "App_Offline.htm" -ItemType "file" -Value "application updates in process..."
          }
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'config'
        nugetConfigPath: 'web/NuGet.config'
        externalFeedCredentials: 'TC Nuget'  
    - task: replacetokens@4
      inputs:
        targetFiles: '**/appsettings.json'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        useLegacyPattern: false
        enableTelemetry: true
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-f netcoreapp3.1 --self-contained true -r  win-x64 -p:PublishDir=.\publish /p:Configuration=Release /p:EnvironmentName=DEV'
        zipAfterPublish: false
        modifyOutputPath: false
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)\\Web\\publish\\'
        Contents: '**'
        TargetFolder: '\\ncrws541\DEV\WAA'
        CleanTargetFolder: true
        retryCount: '5'



